### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by MrAtiebatie** [AndreasHeiberg/laravel-notify#1]
Hi, I get an error while cloning your package with composer. 

`[RuntimeException]                                                                                                                                                              
Could not load package andheiberg/notify in https://packagist.org: [UnexpectedValueException]  Could not parse version constraint >=4.0.0 <6.0.0: Invalid version string "4.0.0  
<6.0.0"`

Maybe this can help you:
http://stackoverflow.com/questions/26277151/force-composer-to-require-php-version-between-version-x-and-version-y

**Comment by andheiberg** [comment]
I think this should fix it?

**Comment by MrAtiebatie** [comment]
Seems to work now :)
